# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
